# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a701f66b3465ac84b54c12723551cc6ab84eb0bf023a692918354b653ca56552124e90e7765247d8cee04933c178ee81f23bf619ef9922c609bcd7cf9cd661b

test:
  secret_key_base: af0e4a131f6aa557dd7ae673d9b69653fa9642c3ef002c1ee76f56bb4adf856be95e61ec42be39ff253f891a1c62d46c6a74fa9d4edfc1b6805655e5d0297f9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
